let items = ["ZEzMpdj", "ZEzMpdj", "ZEzMpdj","ZEzMpdj", "LYPqaME", "OBPJKK", "KKPeOPm", "qBWVMop", "PoYepvR", "bpxgWZ", "evxZpZ", "MJKNJZ", "XPQyMo", "JXVpgp", "YNPaaQ", "QmXOOR", "MQRGOe", "zBLGYN", "mGGPXj", "VEZvdg", "XNQaym", "oXpWbd", "oPOVOL", "bqjBMv", "bvpprw", "oaWdOm", "bvgWrO", "ZMbLNM", "eZQKEr", "xywaoW", "yKOMmV", "YNyKpd", "ygNVYM", "QpwZqJ", "rNBZZqv", "gPmNwv", "pJjOGW", "Kxygqv", "QyBKvW", "azVXym", "obyLPe", "dNKKOw", "VPLgaV", "pNZzMg", "qJNRaL", "yNvKpp", "wgwdzr", "WNeEgZx", "LYPBQvW", "GRgZExW", "YzPxWyW", "LYEjxyG"];
let num = ["one", "two", "three", "four", "five", "six"];
let randomItem = `<a class="random" href="https://www.youtube.com/channel/UChQwoiT46RYC91SOGwl3oNw/channels?view_as=subscriber/${items[Math.floor(Math.random() * items.length)]}" target="_blank"><div class="card fas fa-dice-${num[Math.floor(Math.random() * num.length)]}"></div></a>`
var button = button || true;

if(window.location.href.indexOf("fullcpgrid") == -1 /*Small on pages*/ && window.location.href.indexOf("debug") /*...debug, mentioned for whenever I forget how to read code*/ == -1 && window.location.href.indexOf("fullembedgrid") == -1 /*Focused/details*/) { //Don't show on these pages
   document.body.innerHTML +=
   `<link href="./body.css" rel="stylesheet"><div style=position:fixed;bottom:-5rem;right:-5rem; id=user-button><div class=icons style=position:absolute;z-index:950;top:50%;left:50%;width:0;height:0%;opacity:0;><a href=https://www.linkedin.com/in/dilipkumar-kommanaboina target=_blank><div class="card fab fa-linkedin"></div></a><a href=https://github.com/kdk2933 target=_blank><div class="card fab fa-github"></div></a><a href=https://codepen.io/kdk2933 target=_blank><div class="card fab fa-codepen"></div></a>${randomItem}</div><div class="card main"style=position:relative;z-index:1000;width:4rem;height:4rem;display:grid;place-items:center;background:var(--user-button-background)><img alt=""class="height:100%; width:100%;"src=assets/img/Mask.png></div>`}

